CREATE DATABASE IF NOT EXISTS tecnologias_db;
USE tecnologias_db;

CREATE TABLE IF NOT EXISTS `tecnologias_db`.`tb_nome_da_tecnologia1` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `DATA` DATE NOT NULL,
  `HORA` TIME NOT NULL,
  `MOTORISTA` VARCHAR(255) DEFAULT NULL,
  `DURACAO` TIME NOT NULL,
  `EXCESSO` INT(3) NOT NULL,
  `LIMIAR` INT(3) NOT NULL,
  `LATITUDE` VARCHAR(45) DEFAULT NULL,
  `LONGITUDE` VARCHAR(45) DEFAULT NULL,
  `PLACA` VARCHAR(8) NOT NULL,
  `ALERTA` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tecnologias_db`.`tb_tecnologia_2` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `MOTORISTA` VARCHAR(255) DEFAULT NULL,
  `DURACAO` TIME NOT NULL,
  `EXCESSO` INT(3) NOT NULL,
  `LIMIAR` INT(3) NOT NULL,
  `ALERTA` VARCHAR(80) NOT NULL,
  `DATA` DATE NOT NULL,
  `HORA` TIME NOT NULL,
  `PLACA` VARCHAR(8) NOT NULL,
  `LATITUDE` VARCHAR(45) DEFAULT NULL,
  `LONGITUDE` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tecnologias_db`.`tb_tecnologia_3` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `PLACA` VARCHAR(8) NOT NULL,
  `MOTORISTA` VARCHAR(255) DEFAULT NULL,
  `ALERTA` VARCHAR(80) NOT NULL,
  `EXCESSO` INT(3) NOT NULL,
  `DURACAO` TIME NOT NULL,
  `DATA` DATE NOT NULL,
  `HORA` TIME NOT NULL,
  `LATITUDE` VARCHAR(45) DEFAULT NULL,
  `LONGITUDE` VARCHAR(45) DEFAULT NULL,
  `LIMIAR` INT(3) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tecnologias_db`.`tb_tecnologia_4` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `LIMIAR` INT(3) NOT NULL,
  `EXCESSO` INT(3) NOT NULL,
  `DURACAO` TIME NOT NULL,
  `PLACA` VARCHAR(8) NOT NULL,
  `DATA` DATE NOT NULL,
  `HORA` TIME NOT NULL,
  `MOTORISTA` VARCHAR(255) DEFAULT NULL,
  `ALERTA` VARCHAR(80) NOT NULL,
  `LATITUDE` VARCHAR(45) DEFAULT NULL,
  `LONGITUDE` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tecnologias_db`.`tb_tecnologia_5` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `MOTORISTA` VARCHAR(255) DEFAULT NULL,
  `DURACAO` TIME NOT NULL,
  `EXCESSO` INT(3) NOT NULL,
  `LIMIAR` INT(3) NOT NULL,
  `ALERTA` VARCHAR(80) NOT NULL,
  `DATA` DATE NOT NULL,
  `HORA` TIME NOT NULL,
  `PLACA` VARCHAR(8) NOT NULL,
  `LATITUDE` VARCHAR(45) DEFAULT NULL,
  `LONGITUDE` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tecnologias_db`.`tb_tecnologia_6` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `MOTORISTA` VARCHAR(80) NOT NULL,
  `EXCESSO` DECIMAL(10,2) NOT NULL,
  `DATA` DATE NOT NULL,
  `HORA` TIME NOT NULL,
  `PLACA` VARCHAR(8) NOT NULL,
  `ALERTA` VARCHAR(80) NOT NULL,
  `LIMIAR` INT(3) NOT NULL,
  `DURACAO` TIME NOT NULL,
  `LATITUDE` VARCHAR(45) DEFAULT NULL,
  `LONGITUDE` VARCHAR (45) DEFAULT null,
  PRIMARY KEY (`id`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tecnologias_db`.`tb_tecnologia_7` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `DATA` DATE NOT NULL,
  `KM` DECIMAL(10,2) NOT NULL,
  `PLACA` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tecnologias_db`.`tb_tecnologia_8` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `DATA` DATE NOT NULL,
  `KM` DECIMAL(10,2) NOT NULL,
  `PLACA` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tecnologias_db`.`tb_tecnologia_9` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `DATA` DATE NOT NULL,
  `KM` DECIMAL(10,2) NOT NULL,
  `PLACA` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tecnologias_db`.`tb_tecnologia_10` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `DATA` DATE NOT NULL,
  `KM` DECIMAL(10,2) NOT NULL,
  `PLACA` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tecnologias_db`.`tb_tecnologia_11` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `MOTORISTA` VARCHAR(255) DEFAULT NULL,
  `DEPARTAMENTO` VARCHAR(80) DEFAULT NULL,
  `DIA` DATE NOT NULL,
  `KM` DECIMAL(10,2) NOT NULL,
  `DATA_INICIO` DATE NOT NULL,
  `HORA_INICIO` TIME NOT NULL,
  `DATA_FIM` DATE NOT NULL,
  `HORA_FIM` TIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tecnologias_db`.`tb_tecnologia_12` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `MOTORISTA` VARCHAR(255) DEFAULT NULL,
  `ALERTA` VARCHAR(80) NOT NULL,
  `VALIDACAO` VARCHAR(80) DEFAULT NULL,
  `DATA` DATE NOT NULL,
  `HORA` TIME NOT NULL,
  `PLACA` VARCHAR(8) NOT NULL,
  `LATITUDE` VARCHAR(45) DEFAULT NULL,
  `LONGITUDE` VARCHAR(45) DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tecnologias_db`.`tb_tecnologia_13` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ALERTA` VARCHAR(80) NOT NULL,
  `DATA` DATE NOT NULL,
  `HORA` TIME NOT NULL,
  `MOTORISTA` VARCHAR(255) DEFAULT NULL,
  `VALIDACAO` VARCHAR(80) DEFAULT NULL,
  `LATITUDE` VARCHAR(45) DEFAULT NULL,
  `LONGITUDE` VARCHAR(45) DEFAULT NULL,
  `PLACA` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tecnologias_db`.`tb_tecnologia_14` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ALERTA` VARCHAR(80) NOT NULL,
  `PLACA` VARCHAR(8) NOT NULL,
  `MOTORISTA` VARCHAR(255) DEFAULT NULL,
  `VALIDACAO` VARCHAR(80) NOT NULL,
  `LATITUDE` VARCHAR(45) DEFAULT NULL,
  `LONGITUDE` VARCHAR(45) DEFAULT NULL,
  `DATA` DATE NOT NULL,
  `HORA` TIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tecnologias_db`.`tb_tecnologia_15` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `DATA` DATE NOT NULL,
  `HORA` TIME NOT NULL,
  `MOTORISTA` VARCHAR(255) DEFAULT NULL,
  `DURACAO` TIME NOT NULL,
  `EXCESSO` INT NOT NULL,
  `PONTO_REFERENCIA` VARCHAR(255) DEFAULT NULL,
  `PLACA` VARCHAR(8) NOT NULL,
  `LATITUDE` VARCHAR(45) DEFAULT NULL,
  `LONGITUDE` VARCHAR(45) DEFAULT NULL,
  `LIMIAR` INT NOT NULL,
  `ALERTA` VARCHAR(80) NOT NULL,
  `CATEGORIA` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tecnologias_db`.`tb_tecnologia_16` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `PLACA` VARCHAR(8) NOT NULL,
  `LIMIAR` INT NOT NULL,
  `MOTORISTA` VARCHAR(255) DEFAULT NULL,
  `PONTO_REFERENCIA` VARCHAR(255) DEFAULT NULL,
  `DURACAO` TIME NOT NULL,
  `EXCESSO` INT NOT NULL,
  `LATITUDE` VARCHAR(45) DEFAULT NULL,
  `LONGITUDE` VARCHAR(45) DEFAULT NULL,
  `DATA` DATE NOT NULL,
  `HORA` TIME NOT NULL,
  `CATEGORIA` VARCHAR(80) NOT NULL,
  `ALERTA` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tecnologias_db`.`tb_tecnologia_17` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `PLACA` VARCHAR(8) NOT NULL,
  `MOTORISTA` VARCHAR(255) DEFAULT NULL,
  `PONTO_REFERENCIA` VARCHAR(255) DEFAULT NULL,
  `EXCESSO` FLOAT NOT NULL,
  `DURACAO` TIME NOT NULL,
  `DATA` DATE NOT NULL,
  `HORA` TIME NOT NULL,
  `LATITUDE` VARCHAR(45) DEFAULT NULL,
  `LONGITUDE` VARCHAR(45) DEFAULT NULL,
  `LIMIAR` INT NOT NULL,
  `CATEGORIA` VARCHAR(80) NOT NULL,
  `ALERTA` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB